### ISSUE TITLE
Update wiped out all custom files

### ISSUE THREAD

**Issue by agneevX** [litinoveweedle/SmartIR#11]
Hello,

After updating to 1.17.13, all of my json files that I painstakingly created over the years got deleted.

There is nothing in /custom_codes.

**Comment by tayanov** [comment]
+1 delete my personal code from "codes" folder too

**Comment by litinoveweedle** [comment]
Hello sorry for the deleting files, although it is not completely my fault ;-) But I should probably put BIGGER warning into Manifest. I hope that you have backup.

Delete of the custom codes files is not caused by the integration, but by the HACS as the directory for custom codes changed (and this is noted in the changes manifest and also in the documentation) Only `custom_codes` directory is now persistent, so it is not wiped out and replaced by HACS during integration update. While original `codes` directory is being updated by HACS and therefore allows for new codes to be automatically delivered during integration update. It is [documented here](https://github.com/litinoveweedle/SmartIR?tab=readme-ov-file#device-data---ir-codes). So sorry to say, but this is not a bug, but rather intended functionality.
